FEATURES_REQUIRED += periph_uart

ifneq (,$(filter slipdev_stdio,$(USEMODULE)))
  USEMODULE += isrpipe
endif

ifneq (,$(filter slipdev_config,$(USEMODULE)))
  USEMODULE += chunked_ringbuffer
  USEMODULE += checksum
  USEMODULE += sock_udp
  USEMODULE += gnrc_ipv6
  USEMODULE += nanocoap_sock
  USEMODULE += nanocoap_resources
endif
