$(warning   base is $(RIOTBASE))

include ../../Makefile.tests_common

$(warning   base is $(RIOTBASE))


USEMODULE += ad7746
USEMODULE += ztimer
USEMODULE += ztimer_msec

include $(RIOTBASE)/Makefile.include

$(warning   base is $(RIOTBASE))
